//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string BrandName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> Availability { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
